```{r}
library(tidyverse)
library(here)
library(nflreadr)
theme_set(theme_light())
```

```{r}
games <- read_csv(here("nfl-big-data-bowl-2024", "games.csv"))
plays <- read_csv(here("nfl-big-data-bowl-2024", "plays.csv"))
players <- read_csv(here("nfl-big-data-bowl-2024", "players.csv"))
tackles <- read_csv(here("nfl-big-data-bowl-2024", "tackles.csv"))

tracking <- list.files(path = here("nfl-big-data-bowl-2024"), full.names = TRUE) %>% 
  str_subset("tracking_week_") %>% 
  map(read_csv) %>% 
  list_rbind()
```

```{r}
tracking <- tracking %>%
  mutate(
    # make all plays go from left to right
    x = ifelse(playDirection == "left", 120 - x, x),
    y = ifelse(playDirection == "left", 160 / 3 - y, y),
    # flip player direction and orientation
    dir = ifelse(playDirection == "left", dir + 180, dir),
    dir = ifelse(dir > 360, dir - 360, dir),
    o = ifelse(playDirection == "left", o + 180, o),
    o = ifelse(o > 360, o - 360, o),
    dir_rad = pi * (dir / 180),
    # get orientation and direction in x and y direction
    # NA checks are for the ball
    dir_x = ifelse(is.na(dir), NA_real_, sin(dir_rad)),
    dir_y = ifelse(is.na(dir), NA_real_, cos(dir_rad)),
    # Get directional speed/velo
    s_x = dir_x * s,
    s_y = dir_y * s,
    # Get directional acceleration
    a_x = dir_x * a,
    a_y = dir_y * a
  )
```

```{r}
pbp22 <- load_pbp(seasons = 2022)
```

```{r}
runs <- pbp22 %>% 
  filter(play_type == "run") %>% 
  distinct(gameId = as.double(old_game_id), 
           playId = as.double(play_id))

# Focuses on plays where Running Backs are the Ball Carriers
rb_bc_plays <- plays %>% 
  semi_join(runs, by = c("gameId", "playId")) %>% 
  left_join(select(players, nflId, position), by = c("ballCarrierId" = "nflId")) %>% 
  filter(position == "RB") %>% 
  select(gameId, playId, ballCarrierDisplayName, position)
```

```{r}
end_event <- tracking %>% 
  inner_join(runs) %>% 
  distinct(gameId, playId, frameId, event) %>% 
  inner_join(rb_bc_plays) %>% 
  filter(event %in% c("fumble", "fumble_defense_recovered", "fumble_offense_recovered",
                      "out_of_bounds", "safety", "tackle", "touchdown")) %>%
  # count(gameId, playId, sort = TRUE)
  # correct 1 play where there's a safety after a tackle
  group_by(gameId, playId) %>% 
  slice_min(frameId) %>% 
  select(gameId, playId, end_frame = frameId)

# start of play event
start_event <- tracking %>% 
  inner_join(runs) %>% 
  distinct(gameId, playId, frameId, event) %>% 
  inner_join(rb_bc_plays) %>% 
  filter(event %in% c("ball_snap", "autoevent_ballsnap", "snap_direct")) %>% 
  group_by(gameId, playId) %>% 
  slice_min(frameId) %>% 
  distinct(gameId, playId, start_frame = frameId)

frames <- start_event  %>%
  full_join(end_event)
```

```{r}
tracking_runs <- tracking %>% 
  inner_join(frames) %>% 
  filter(frameId >= start_frame, frameId <= end_frame) %>% 
  left_join(select(players, nflId, weight)) %>% 
  mutate(m_x = s_x * weight, m_y = s_y * weight)
```

```{r}
# Filter datasets to include only RB ball carrier run plays 

games <- games %>%
  semi_join(rb_bc_plays, by = "gameId")  # Filter games by gameId only

plays <- plays %>%
  semi_join(runs, by = c("gameId", "playId")) %>%
  semi_join(rb_bc_plays, by = c("gameId", "playId"))  # Filter plays by both gameId and playId

tracking <- tracking %>%
  semi_join(runs, by = c("gameId", "playId")) %>%
  semi_join(rb_bc_plays, by = c("gameId", "playId"))  # Filter tracking data by both gameId and playId

tracking_runs <- tracking_runs %>%
  semi_join(runs, by = c("gameId", "playId")) %>%
  semi_join(rb_bc_plays, by = c("gameId", "playId"))  # Filter tracking runs data 
```

```{r}
# Save each dataset to an RDS file
saveRDS(games, "data/games.rds")
saveRDS(plays, "data/plays.rds")
saveRDS(players, "data/players.rds")
saveRDS(tackles, "data/tackles.rds")
saveRDS(tracking, "data/tracking.rds")
saveRDS(tracking_runs, "data/tracking_runs.rds")
saveRDS(frames, "data/frames.rds")
saveRDS(pbp22, "data/pbp22.rds")
saveRDS(runs, "data/runs.rds")
saveRDS(rb_bc_plays, "data/rb_bc_plays.rds")
```